[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_access_anchor = "CwswgaYiDLpgN2sWQpbcyWYWTk7sVM8sfkvS6nSnWB63"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
